services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: projeto_gis_postgis
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    restart: unless-stopped
